# ##image classification using Keras build in generator

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

KeyboardInterrupt: 

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("nunenuh/pytorch-challange-flower-dataset")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/pytorch-challange-flower-dataset


In [2]:

import numpy as np
import pandas as pd
import os
for dirname, _, filenames in os.walk('/kaggle/input/pytorch-challange-flower-dataset/'):
    print(dirname)
    for filename in filenames:
        print(os.path.join(dirname, filename))


Streaming output truncated to the last 5000 lines.
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04233.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04183.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04203.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04201.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04219.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04179.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04194.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04212.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04224.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04176.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image_04188.jpg
/kaggle/input/pytorch-challange-flower-dataset/dataset/train/52/image

In [5]:
import matplotlib
matplotlib.use("Agg")
# import the necessary packages
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.preprocessing.image import img_to_array
import matplotlib.pyplot as plt
import numpy as np
import argparse
import random
import cv2
import os

In [3]:
train_dir="/kaggle/input/pytorch-challange-flower-dataset/dataset/train/"
valid_dir="/kaggle/input/pytorch-challange-flower-dataset/dataset/valid/"
#test_dir="/content/drive/MyDrive/AY2024-25/Deep Learning/Datasets/VegetableDataset/test/"

In [6]:
train_gen=ImageDataGenerator(rescale=1./255)
val_gen=ImageDataGenerator(rescale=1./255)
#test_gen=ImageDataGenerator(rescale=1./255)

In [7]:
train_data=train_gen.flow_from_directory(train_dir,target_size=(224,224),
                                         batch_size=32,class_mode='categorical')
valid_data=val_gen.flow_from_directory(valid_dir,target_size=(224,224),
                                         batch_size=32,class_mode='categorical')


Found 6552 images belonging to 102 classes.
Found 818 images belonging to 102 classes.


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
# Retrieve one batch of images and labels
images, labels = next(train_data)
print(images.shape,labels)
# Display the first image in the batch
plt.imshow(images[0])
plt.axis('off')  # Hide axis
plt.title(f"Label: {int(labels)}")  # Display label
plt.show()

(32, 224, 224, 3) [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
class_indices = train_data.class_indices
print(class_indices)

{'apple': 0, 'banana': 1, 'beetroot': 2, 'bell pepper': 3, 'cabbage': 4, 'capsicum': 5, 'carrot': 6, 'cauliflower': 7, 'chilli pepper': 8, 'corn': 9, 'cucumber': 10, 'eggplant': 11, 'garlic': 12, 'ginger': 13, 'grapes': 14, 'jalepeno': 15, 'kiwi': 16, 'lemon': 17, 'lettuce': 18, 'mango': 19, 'onion': 20, 'orange': 21, 'paprika': 22, 'pear': 23, 'peas': 24, 'pineapple': 25, 'pomegranate': 26, 'potato': 27, 'raddish': 28, 'soy beans': 29, 'spinach': 30, 'sweetcorn': 31, 'sweetpotato': 32, 'tomato': 33, 'turnip': 34, 'watermelon': 35}


In [ ]:
# import the necessary packages
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Activation
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras import backend as K

model = Sequential()
inputShape = (224, 224, 3)

# if we are using "channels first", update the input shape
if K.image_data_format() == "channels_first":
			inputShape = (3,224,224)

# first set of CONV => RELU => POOL layers
model.add(Conv2D(16, (3, 3), padding="same",
		input_shape=inputShape))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))

# second set of CONV => RELU => POOL layers
model.add(Conv2D(32, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))

# third set of CONV => RELU => POOL layers
model.add(Conv2D(64, (3, 3), padding="same"))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))

model.add(Flatten())
model.add(Dense(1024))
model.add(Activation("relu"))

# sigmoid classifier
model.add(Dense(102, activation="softmax"))
#model.add(Activation("softmax"))

In [ ]:
#Compile the model
print("[INFO] compiling model...")
opt = Adam()
model.compile(loss="categorical_crossentropy", optimizer=opt,
	metrics=["accuracy"])

[INFO] compiling model...


In [ ]:
# Define the checkpoint callback
checkpoint =tensorflow.keras.callbacks.ModelCheckpoint(
    filepath='path/model_epoch_{epoch:02d}.h5',  # Save the model with epoch number
    save_freq='epoch',                      # Save at the end of every epoch
    save_weights_only=False,                # Save the entire model (architecture + weights)
    verbose=1                               # Print a message when saving
)

NameError: name 'tensorflow' is not defined

In [ ]:
#train the model
# train the network
print("[INFO] training network...")
H = model.fit(train_data,
            validation_data=valid_data,
						steps_per_epoch=100,
						callbacks=[checkpoint],
						epochs=10)


[INFO] training network...
Epoch 1/10
 10/100 [==>...........................] - ETA: 11:35 - loss: 4.9775 - accuracy: 0.4209

KeyboardInterrupt: ignored

In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
model = load_model('your_model.h5')  # Replace with your model's filename

# Load the image with the same target size as used during training
img = load_img('path_to_image.jpg', target_size=(224,224))  # Replace with your image path and target size

# Convert the image to a NumPy array
img_array = img_to_array(img)

# Normalize the image data if the model was trained on normalized data
img_array = img_array / 255.0  # Apply this step only if normalization was used during training

# Expand dimensions to match the model's input shape (1, height, width, channels)
img_array = np.expand_dims(img_array, axis=0)
predictions = model.predict(img_array)
predicted_class = np.argmax(predictions, axis=1)
print(predicted_class[0]) ## numerically
print(class_indices[predicted_class[0]]) ## categorical prediction