Rupesh Bharambe (AI3107)

In [1]:
import numpy as np
import pandas as pd

In [2]:
path="IMDB Dataset.xlsx"
df = pd.read_excel(path)

In [3]:
df=df.iloc[:20000]

In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [6]:
df['sentiment'][1]

'positive'

In [7]:
df['sentiment'].value_counts()

sentiment
negative    10097
positive     9903
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

74

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

0

In [12]:
# Basic Preprocessing
# Remove tags
# lowercase
# remove stopwords

In [13]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'), '', raw_text)
    return cleaned_text

In [14]:
df['review'] = df['review'].apply(remove_tags)

In [15]:
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. The filming tec...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
19995  ok. for starters, taxi driver is amazing. this...  negative
19996  It's sort of hard for me to say it, because I ...  negative
19997  I still liked it though. Warren Beatty is only...  positive
19998  We could still use Black Adder even today. Ima...  positive
19999  This so-called "documentary" tries to tell tha...  negative

[19926 rows x 2 columns]

In [16]:
df['review'] = df['review'].apply(lambda x:x.lower())

In [17]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\rupes\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [18]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')
print(sw_list)
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she

In [19]:
df

review sentiment
0      one reviewers mentioned watching 1 oz episode ...  positive
1      wonderful little production. filming technique...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically there's family little boy (jake) thi...  negative
4      petter mattei's "love time money" visually stu...  positive
...                                                  ...       ...
19995  ok. starters, taxi driver amazing. this, taxi ...  negative
19996  sort hard say it, greatly enjoyed "targets" "p...  negative
19997  still liked though. warren beatty fair comic b...  positive
19998  could still use black adder even today. imagin...  positive
19999  so-called "documentary" tries tell usa faked m...  negative

[19926 rows x 2 columns]

In [20]:
X = df.iloc[:,0:1]
y = df['sentiment']

In [21]:
X

review
0      one reviewers mentioned watching 1 oz episode ...
1      wonderful little production. filming technique...
2      thought wonderful way spend time hot summer we...
3      basically there's family little boy (jake) thi...
4      petter mattei's "love time money" visually stu...
...                                                  ...
19995  ok. starters, taxi driver amazing. this, taxi ...
19996  sort hard say it, greatly enjoyed "targets" "p...
19997  still liked though. warren beatty fair comic b...
19998  could still use black adder even today. imagin...
19999  so-called "documentary" tries tell usa faked m...

[19926 rows x 1 columns]

In [22]:
y

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
19995    negative
19996    negative
19997    positive
19998    positive
19999    negative
Name: sentiment, Length: 19926, dtype: object

In [23]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(y)

In [24]:
y

array([1, 1, 1, ..., 1, 1, 0])

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [26]:
X_train.shape

(15940, 1)

In [27]:
# Applying BoW
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
cv = CountVectorizer()
cv=TfidfVectorizer()

In [29]:
X_train_bow = cv.fit_transform(X_train['review']).toarray()
X_test_bow = cv.transform(X_test['review']).toarray()

In [30]:
X_train_bow.shape

(15940, 64539)

In [31]:
print(X_train_bow[1])

[0. 0. 0. ... 0. 0. 0.]


In [32]:
X_train_bow[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [33]:
print(y_train[0])

1


In [34]:
(X_train_bow,y_train,X_test_bow,y_test)

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1, 0, 0, ..., 0, 0, 1]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]),
 array([1, 0, 0, ..., 0, 1, 1]))

In [35]:
# Save vectorizer
import pickle
with open("vectorizer.pkl", "wb") as f:
    pickle.dump(cv, f)

In [36]:
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
# Save the full model (best only)
checkpoint_cb = ModelCheckpoint(
    filepath="best_model.h5",          # Full model path
    monitor="val_loss",
    mode="min",
    save_best_only=True,              # Save only the best model
    verbose=1
)


In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import load_model

# Recreate model architecture
model = Sequential([
    Dense(64, input_dim=X_train_bow.shape[1], activation='relu'),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

C:\Users\rupes\AppData\Roaming\Python\Python311\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [40]:

model.fit(
    X_train_bow, y_train,
    epochs=10,
    batch_size=2,
    validation_data=(X_test_bow,y_test),
    callbacks=[
        EarlyStopping(monitor='val_loss', patience=2),
        checkpoint_cb
    ],
    verbose=1
)

Epoch 1/10
7970/7970 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.8198 - loss: 0.3923
Epoch 1: val_loss improved from inf to 0.25712, saving model to best_model.h5


7970/7970 ━━━━━━━━━━━━━━━━━━━━ 345s 43ms/step - accuracy: 0.8198 - loss: 0.3923 - val_accuracy: 0.8916 - val_loss: 0.2571
Epoch 2/10
7970/7970 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9667 - loss: 0.0968
Epoch 2: val_loss did not improve from 0.25712
7970/7970 ━━━━━━━━━━━━━━━━━━━━ 326s 41ms/step - accuracy: 0.9667 - loss: 0.0968 - val_accuracy: 0.8846 - val_loss: 0.3289
Epoch 3/10
7969/7970 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9867 - loss: 0.0350
Epoch 3: val_loss did not improve from 0.25712
7970/7970 ━━━━━━━━━━━━━━━━━━━━ 329s 41ms/step - accuracy: 0.9866 - loss: 0.0350 - val_accuracy: 0.8763 - val_loss: 0.4551


In [41]:
import pickle
from tensorflow.keras.models import load_model
import numpy as np

# Load saved vectorizer
with open("vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)

# Load saved best model
model = load_model("best_model.h5")

# Function to predict sentiment
def predict_sentiment(review: str):
    # Vectorize and convert to float32
    vec = vectorizer.transform([review]).toarray().astype('float32')

    # Predict
    prob = model.predict(vec)[0][0]
    label = "Positive" if prob > 0.5 else "Negative"

    print(f"Review: {review}")
    print(f"Sentiment: {label} (Confidence: {prob:.2f})")

# Test predictions
predict_sentiment("superb movie!")
predict_sentiment("It was a terrible and boring movie.")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
Review: superb movie!
Sentiment: Positive (Confidence: 0.98)
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Review: It was a terrible and boring movie.
Sentiment: Negative (Confidence: 0.00)
